### ISSUE TITLE
Please provide LICENSE

### ISSUE THREAD

**Issue by remicollet** [phpDocumentor/ReflectionDocBlock#40]
From License term:

    The above copyright notice and this permission notice shall be included in
    all copies or substantial portions of the Software.

Without this file, redistribution of this library violates its License.

**Comment by remicollet** [comment]
Can you please fix this trivial issue ? 

@sebastianbergmann I think you are also affected by this issue, as PHPUnit 4.5 going to bundled phpspec/prophecy and phpdocumentor/reflection-docblock

**Comment by mvriel** [comment]
I have merged the commit; sorry about not doing it before but due to personal circumstances my OSS time is quite limited at the moment

**Comment by cebe** [comment]
Thanks for taking the time then, hope you are doing well!

**Comment by remicollet** [comment]
@mvriel sorry, but I still don't see the merge nor the license file.

**Comment by remicollet** [comment]
I see it now, thanks.
